### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by Spence1115** [nichestudio/ACF-Markdown#1]
Hey

I know you've not updated in a while, but on the off chance you're interested in maintaining this, is this supposed to work with the wordpress rest api?

**Comment by diogoterremoto** [comment]
Using the REST API with this plugin didn't work for me. It seems that the parser `new \cebe\markdown\GithubMarkdown()` on line 106 of `class-markdown.php` can't be found.

As such, I added a condition to return the value before parsing, like the following:
```
if ( defined('REST_REQUEST') && REST_REQUEST ) {
	return $value;
}
```

Works for my use case, as I would like to parse the Markdown on the client side.

---

EDIT: The edit can be seen [here](https://github.com/diogoterremoto/ACF-Markdown/blob/08c162226d78e4beaac5f584b52fb691bd2dccbc/fields/class-markdown.php#L106).
